language: java
install: skip
jdk: oraclejdk11
before_install:
- chmod +x gradlew
script:
  - ./gradlew build 

before_deploy:
     # Set up git user name and tag this commit
     - git config --local user.name "YOUR GIT USER NAME"
     - git config --local user.email "YOUR GIT USER EMAIL"
     - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
     - git tag $TRAVIS_TAG
deploy:
  - provider: releases
    api_key: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
    skip_cleanup: true
    overwrite: true
    draft: false
    on:
      tags: true
      all_branches: true
    name: $TRAVIS_TAG

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/